let data = [
    {
      "minimumExperience": 97,
      "maximumExperience": 85,
      "minimumSalary": 45,
      "maximumSalary": 21,
      "totalEmployee": 85,
      "applyType": "quick",
      "title": "title 1",
      "companyName": "companyName 1",
      "industry": "IT",
      "location": "fjfbdsbf",
      "remoteType": "remoteType 1",
      "id": "1",
      "job_title": "TEJA",
      "company_name": "12313",
      "remote_type": "wfh",
      "exp_min": "1212",
      "exp_max": "321421312",
      "sal_min": "34252452",
      "sal_max": "454365634",
      "total_emp": "45345435"
    },
    {
      "minimumExperience": "2",
      "maximumExperience": "5",
      "minimumSalary": "2000000",
      "maximumSalary": "200000000",
      "totalEmployee": "1212",
      "applyType": "Front end Dev",
      "title": "title 2",
      "companyName": "Flyerssoft",
      "industry": "IT",
      "location": "Chennai",
      "remoteType": "Remote",
      "id": "2"
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": 74,
      "applyType": "",
      "title": "title 3",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "remoteType 3",
      "id": "3",
      "details": ""
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": 69,
      "applyType": "",
      "title": "title 4",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "remoteType 4",
      "id": "4",
      "details": ""
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": "",
      "applyType": "",
      "title": "title 5",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "",
      "id": "5"
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": "",
      "applyType": "",
      "title": "title 6",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "",
      "id": "6"
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": "",
      "applyType": "",
      "title": "title 7",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "",
      "id": "7"
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": 59,
      "applyType": "",
      "title": "title 8",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "remoteType 8",
      "id": "8",
      "details": ""
    },
    {
      "minimumExperience": "",
      "maximumExperience": "",
      "minimumSalary": "",
      "maximumSalary": "",
      "totalEmployee": "",
      "applyType": "",
      "title": "title 9",
      "companyName": "",
      "industry": "",
      "location": "",
      "remoteType": "",
      "id": "9"
    }
  ]